max_radius: 4.
field_cutoff: 6.
std_theta_degree: 45.
std_X: 5.
# ranges: [[-23., 23.],
#          [-23., 23.],
#          [-1., 40.]]
ranges: [[-27., 27.],
         [-27., 27.],
         [-1., 45.]]
irreps_descriptor: "10x0e + 10x1e + 4x2e + 2x3e"
sh_lmax_descriptor: 3
number_of_basis_descriptor: 10
irrep_normalization: 'norm'
tp_type: 'direct'

N_query: 50
# N_query: 10
query_radius: 3.
#query_radius: 2.5
max_radius_Q: 4.
field_cutoff_Q: 5.
# ranges_Q: [[-15., 15.],
#            [-15., 15.],
#            [-10., 10.]]
ranges_Q: [[-40., 40.],
           [-40., 40.],
           [-0., 60.]]
irreps_out_Q: "10x0e + 10x1e + 4x2e + 2x3e"
sh_lmax_descriptor_Q: 3
number_of_basis_descriptor_Q: 10
irrep_normalization_Q: 'norm'
learnable_query: False

mh_iter: 500
langevin_iter: 100



